apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: daily-todos
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wiki-daily-reading
            image: georgemihail/wiki-daily-reading:latest
            args:
              - /bin/sh
              - script.sh
          restartPolicy: OnFailure