apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackend
  template:
    metadata:
      labels:
        app: todobackend
    spec:
      containers:
        - name: todobackend
          image: georgemihail/to-do-backend