apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: postgress-ss-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: postgress-ss
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 80