apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/secret.yaml
  - manifests/persistentvolume.yaml 
  - manifests/persistentvolumeclaim.yaml
  - manifests/statefulset.yaml # postgres-db
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - manifests/analysistemplate.yaml
  - manifests/rollout-update.yaml
images:
  - name: TODO-STATIC-IMAGE
    newName: georgemihail/todo-static-healthcheck
  - name: FETCH-PHOTO-IMAGE
    newName: georgemihail/image-fetch-health