apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ping-pong-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ping-pong-backend
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 80