apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-ping-connected
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpongconnected
  template:
    metadata:
      labels:
        app: pingpongconnected
    spec:
      containers:
        - name: main-image-connecting
          image: georgemihail/main-app-gke:latest
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: special-config
                  key: MESSAGE
            - name: PONGURL
              valueFrom:
                configMapKeyRef:
                  name: special-config
                  key: PONGURL
        