apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-connected
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoconnected
  template:
    metadata:
      labels:
        app: todoconnected
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: image-fetch-todo
          image: georgemihail/image-fetch-todo:latest
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/src/image
        - name: todo-connected-front
          image: georgemihail/todo-connected-front:latest
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/src/image
        - name: todo-connected-backend
          image: georgemihail/todo-connected-backend:latest
        