apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todobackendpsg-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-backend-psg
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 80