apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingpongconnected-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: main-ping-connected
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 80